version: "3.8"
services:
  FakeDataGen:
    image: fakedatagenerator:latest 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fakedatagenerator
    hostname: fakedatagenerator
    env_file:
      - .env