version: "3.8"
services:
  FakeDataGen:
    image: fakedatagenerator:latest 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fakedatagenerator
    hostname: fakedatagenerator
    # environment:
    #   - DATABASE=mydb
    #   - USER=postgres-user 
    #   - HOST=localhost
    #   - PASSWORD=postgres-pw
    #   - POR5432
    env_file:
      - .env